version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-34-192-30-15.compute-1.amazonaws.com
            database: d26dog6fjid1hs
            schema: public
            user: lkaatojhlrgqch
            password: 4d66a3c276b43b2120e3758f846e06bc10dca39edc1222ede56c295a8b350c71
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true